export type DepositFieldType = 'text' | 'number' | 'select' | 'textarea' | 'file' | 'date'
export type DepositField = { id: string; name: string; label: string; type: DepositFieldType; required: boolean; placeholder?: string; options?: { label: string; value: string }[]; validation?: { min?: number; max?: number } }
export type DepositMethod = { slug: string; name: string; description: string; logo: string; supportedCurrencies: string[]; minAmount: number; maxAmount?: number; processingTime: string; badge?: string; isActive: boolean; instructions: { label: string; value: string }[]; fields: DepositField[] }

export const depositMethods: DepositMethod[] = [
  { slug: 'vodafone-cash', name: 'Vodafone Cash', description: 'تحويل محلي بالجنيه المصري', logo: 'VF', supportedCurrencies: ['EGP'], minAmount: 100, processingTime: '1 إلى 20 دقيقة', badge: 'الأكثر استخدامًا', isActive: true, instructions: [{ label: 'رقم المحفظة', value: '01034584902' }, { label: 'العمولة', value: '0%' }], fields: [{ id: 'amount', name: 'amount', label: 'مبلغ الإيداع', type: 'number', required: true, placeholder: 'أدخل المبلغ بالجنيه', validation: { min: 100 } }, { id: 'senderPhone', name: 'senderPhone', label: 'رقم هاتف المرسل', type: 'text', required: true, placeholder: '01xxxxxxxxx' }, { id: 'reference', name: 'reference', label: 'مرجع العملية', type: 'text', required: true, placeholder: 'أدخل رقم المرجع' }, { id: 'proof', name: 'proof', label: 'إثبات التحويل', type: 'file', required: true }] },
  { slug: 'usdt', name: 'USDT', description: 'تحويل آمن عبر العملات الرقمية', logo: '₮', supportedCurrencies: ['USD', 'EGP'], minAmount: 10, processingTime: '5 إلى 30 دقيقة', badge: 'USDT', isActive: true, instructions: [{ label: 'عنوان الإيداع', value: 'TXXXXXXXXXXXXXXXXXXXXXXXXXXXX' }, { label: 'العمولة', value: 'حسب الشبكة' }], fields: [{ id: 'amount', name: 'amount', label: 'مبلغ الإيداع', type: 'number', required: true, placeholder: 'أدخل مبلغ USDT', validation: { min: 10 } }, { id: 'network', name: 'network', label: 'الشبكة', type: 'select', required: true, options: [{ label: 'TRC20', value: 'TRC20' }, { label: 'BEP20', value: 'BEP20' }, { label: 'ERC20', value: 'ERC20' }] }, { id: 'txid', name: 'txid', label: 'TXID / هاش العملية', type: 'text', required: true, placeholder: 'أدخل TXID' }, { id: 'proof', name: 'proof', label: 'إثبات التحويل', type: 'file', required: true }] },
  { slug: 'bank-transfer', name: 'تحويل بنكي', description: 'تحويل مباشر إلى الحساب البنكي', logo: 'BK', supportedCurrencies: ['EGP'], minAmount: 500, processingTime: 'خلال يوم عمل', isActive: true, instructions: [{ label: 'رقم الحساب', value: 'يظهر بعد اختيار العملة' }], fields: [{ id: 'amount', name: 'amount', label: 'مبلغ الإيداع', type: 'number', required: true, placeholder: 'أدخل المبلغ', validation: { min: 500 } }, { id: 'senderName', name: 'senderName', label: 'اسم المرسل', type: 'text', required: true }, { id: 'bankName', name: 'bankName', label: 'اسم البنك', type: 'text', required: true }, { id: 'reference', name: 'reference', label: 'مرجع العملية', type: 'text', required: true }, { id: 'date', name: 'date', label: 'تاريخ التحويل', type: 'date', required: true }, { id: 'proof', name: 'proof', label: 'إثبات التحويل', type: 'file', required: true }] },
]

export function getDepositMethod(slug: string) { return depositMethods.find((method) => method.slug === slug && method.isActive) }
