'use client'
import Link from 'next/link'
import { ChevronDown, ClipboardList, Home, WalletCards } from 'lucide-react'
import { routes } from '@/lib/routes'
import { DepositMethodCard } from '@/components/deposit-flow'
import { depositMethods } from '@/lib/deposit-methods'
import { SenoLogo } from '@/components/branding/seno-logo'
import { useFrontendAuth } from '@/components/frontend-auth-provider'
import { SidebarTrigger } from '@/components/global-sidebar'

function Header({ balance, currency }: { balance: number; currency: string }) { return <header className="flex items-center justify-between gap-3 py-5 sm:py-8" dir="ltr"><SenoLogo className="w-40" /><div className="flex items-center gap-3"><div className="flex min-w-0 items-center gap-1 rounded-full border border-amber-500/70 px-2 py-2 text-xs sm:gap-2 sm:px-4 sm:py-3 sm:text-base"><WalletCards className="size-4 shrink-0 text-amber-300 sm:size-5" /><span className="truncate">{balance.toFixed(2)} {currency}</span><ChevronDown className="size-3 shrink-0 text-amber-400 sm:size-4" /></div><SidebarTrigger /></div></header> }
export default function WalletPage() { const { user } = useFrontendAuth(); const balance = user?.balance ?? 0; const currency = user?.preferredCurrency ?? 'EGP'; return <main className="min-h-screen bg-[#050506] pb-28 text-white" dir="rtl"><div className="mx-auto max-w-6xl px-4 sm:px-6"><Header balance={balance} currency={currency} /><section className="rounded-3xl border border-white/15 bg-[#090e12] p-5 shadow-[0_0_28px_rgba(255,0,40,.08)]"><div className="flex items-center gap-4"><div className="grid size-16 place-items-center rounded-2xl border border-amber-400/40 bg-black text-amber-300"><WalletCards className="size-9" /></div><div><h1 className="text-2xl font-black sm:text-3xl">محفظتي</h1><p className="text-zinc-400">الرصيد المتاح</p></div><strong className="mr-auto text-2xl text-amber-300">{balance.toFixed(2)} <small className="text-sm">{currency}</small></strong></div><div className="mt-5 grid grid-cols-2 gap-2 border-t border-white/10 pt-4 sm:grid-cols-4">{['EGP 500.00', 'USD 12.45', 'EUR 11.80', 'SAR 46.20'].map((item, index) => <div key={item} className={`rounded-xl border p-3 text-center text-sm ${index === 0 ? 'border-amber-500/70 text-amber-200' : 'border-white/10 text-zinc-400'}`}>{item}</div>)}</div></section><div className="my-5 flex gap-2 overflow-x-auto rounded-3xl border border-white/10 bg-[#070a0d] p-2"><Link href="#deposit-methods" className="rounded-2xl bg-red-600/20 px-5 py-3 text-sm font-bold text-white">إضافة رصيد</Link><Link href="/wallet/deposits" className="rounded-2xl px-5 py-3 text-sm text-zinc-300 transition hover:bg-white/5 hover:text-amber-200">سجل الإيداعات</Link><Link href={routes.senoCodes} className="rounded-2xl px-5 py-3 text-sm text-zinc-300 transition hover:bg-white/5 hover:text-amber-200">سينو كود</Link></div><section id="deposit-methods" className="py-2"><div className="mb-5"><p className="text-sm text-amber-300">SENO WALLET</p><h2 className="mt-1 text-2xl font-black">طرق الإيداع</h2><p className="text-sm text-zinc-400">اختر طريقة الإيداع المناسبة لك</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{depositMethods.filter((method) => method.isActive).map((method) => <DepositMethodCard key={method.slug} method={method} />)}</div></section></div></main> }
