import Link from 'next/link'
import { ArrowLeft, CheckCircle2, Clock3, ExternalLink, FileImage, WalletCards } from 'lucide-react'
import { getDepositByIdForUser, type DepositStatus } from '@/lib/deposits'

const labels: Record<DepositStatus, string> = { pending: 'Pending', approved: 'Approved', rejected: 'Rejected' }
const styles: Record<DepositStatus, string> = { pending: 'text-amber-200 border-amber-400/30 bg-amber-400/10', approved: 'text-emerald-300 border-emerald-400/30 bg-emerald-400/10', rejected: 'text-red-300 border-red-400/30 bg-red-400/10' }
const date = (value: string) => new Intl.DateTimeFormat('en-US', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value))

export default async function DepositDetailsPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const deposit = getDepositByIdForUser(id, 'demo-user')
  if (!deposit) return <main className="grid min-h-screen place-items-center bg-[#050506] px-6 text-center text-white"><div><h1 className="text-2xl font-black">Deposit not found</h1><Link href="/wallet/deposits" className="mt-5 inline-flex rounded-xl bg-red-600 px-5 py-3 font-bold">Back to Deposit History</Link></div></main>
  const details = [['Deposit ID', deposit.id], ['Amount', `${deposit.amount.toFixed(2)} ${deposit.currency}`], ['Currency', deposit.currency], ['Payment Method', deposit.paymentMethodName], ['Transaction Reference', deposit.transactionReference ?? '—'], ['Created At', date(deposit.createdAt)], ['Updated At', date(deposit.updatedAt)]]
  return <main className="min-h-screen bg-[#050506] px-4 py-8 text-white" dir="ltr"><div className="mx-auto max-w-3xl"><Link href="/wallet/deposits" className="inline-flex items-center gap-2 text-sm text-zinc-400 hover:text-amber-300"><ArrowLeft className="size-4" /> Back to Deposit History</Link><div className="mt-6 rounded-3xl border border-white/10 bg-[#0b1014] p-5 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-center gap-3"><div className="grid size-12 place-items-center rounded-2xl border border-amber-400/30 bg-black text-amber-300"><WalletCards className="size-6" /></div><div><p className="text-sm text-zinc-500">Deposit Details</p><h1 className="text-2xl font-black">{deposit.id}</h1></div></div><span className={`rounded-full border px-3 py-1.5 text-sm font-bold ${styles[deposit.status]}`}>{labels[deposit.status]}</span></div><div className="mt-8 grid gap-3 sm:grid-cols-2">{details.map(([label, value]) => <div key={label} className="rounded-2xl border border-white/10 bg-black/20 p-4"><p className="text-xs text-zinc-500">{label}</p><p className="mt-2 break-words font-semibold text-zinc-100">{value}</p></div>)}</div><section className="mt-8 border-t border-white/10 pt-6"><h2 className="text-lg font-bold">Payment Information</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{deposit.senderName && <Info label="Sender Name" value={deposit.senderName} />}{deposit.senderAccount && <Info label="Sender Account" value={deposit.senderAccount} />}{deposit.network && <Info label="Network" value={deposit.network} />}{deposit.walletAddress && <Info label="Wallet Address" value={deposit.walletAddress} />}{deposit.transactionHash && <Info label="Transaction Hash" value={deposit.transactionHash} />}</div></section>{deposit.receiptUrl ? <section className="mt-8 border-t border-white/10 pt-6"><h2 className="text-lg font-bold">Payment Receipt</h2><a href={deposit.receiptUrl} className="mt-4 inline-flex items-center gap-2 rounded-xl border border-white/10 px-4 py-3 text-sm text-amber-200 hover:border-amber-300"><FileImage className="size-4" /> View Receipt <ExternalLink className="size-4" /></a></section> : <section className="mt-8 border-t border-white/10 pt-6"><p className="text-sm text-zinc-500">Payment Receipt</p><p className="mt-2 text-sm text-zinc-400">No receipt uploaded</p></section>}{deposit.status === 'rejected' && deposit.rejectionReason && <section className="mt-8 rounded-2xl border border-red-400/20 bg-red-400/5 p-4"><h2 className="font-bold text-red-300">Rejection Reason</h2><p className="mt-2 text-sm text-zinc-300">{deposit.rejectionReason}</p></section>}</div></div></main>
}

function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-white/10 bg-black/20 p-4"><p className="text-xs text-zinc-500">{label}</p><p className="mt-2 break-words text-sm text-zinc-200">{value}</p></div> }
