'use client'

import { useMemo, useState } from 'react'
import Link from 'next/link'
import { CheckCircle2, ChevronLeft, Minus, Plus, WalletCards } from 'lucide-react'
import type { Game, GameOrder } from '@/lib/game-data'
import { saveGameOrder } from '@/lib/game-data'
import { useFrontendAuth } from '@/components/frontend-auth-provider'

export function GameTopUpForm({ game, packageId }: { game: Game; packageId: string }) {
  const selected = game.packages.find((item) => item.id === packageId) ?? game.packages[0]
  const { balance, setBalance } = useFrontendAuth()
  const [playerId, setPlayerId] = useState(''); const [quantity, setQuantity] = useState(1); const [error, setError] = useState(''); const [order, setOrder] = useState<GameOrder | null>(null)
  const total = useMemo(() => selected.price * quantity, [selected.price, quantity])
  function purchase() { if (!playerId.trim()) return setError('يرجى إدخال معرف اللاعب'); if (balance < total) return setError('الرصيد غير كافٍ لإتمام عملية الشراء'); const nextBalance = balance - total; const created: GameOrder = { id: `SENO-${Math.floor(100000 + Math.random() * 900000)}`, type: 'game', gameId: game.id, gameName: game.name, packageId: selected.id, package: `${selected.amount.toLocaleString('en-US')} ${selected.unit}`, quantity, playerId: playerId.trim(), unitPrice: selected.price, total, currency: 'USD', status: 'pending', createdAt: new Date().toLocaleString('ar-EG') }; setBalance(nextBalance); saveGameOrder(created); setOrder(created); setError('') }
  if (order) return <section className="mx-auto max-w-2xl rounded-3xl border border-emerald-400/40 bg-[#090d10] p-6 text-center shadow-[0_0_30px_rgba(16,185,129,.12)]"><CheckCircle2 className="mx-auto size-16 text-emerald-300" /><h2 className="mt-5 text-2xl font-black">تم إنشاء الطلب بنجاح</h2><p className="mt-2 text-zinc-400">تم إنشاء طلب شحن اللعبة بنجاح</p><div className="mt-6 grid gap-3 rounded-2xl bg-black/30 p-4 text-right"><p>رقم الطلب: <b className="text-amber-300">{order.id}</b></p><p>الإجمالي: <b>{order.total.toFixed(2)} USD</b></p><p>الرصيد المتبقي: <b className="text-emerald-300">{balance.toFixed(2)} USD</b></p></div><div className="mt-6 flex flex-col gap-3 sm:flex-row"><Link href={`/orders/${order.id}`} className="flex-1 rounded-2xl bg-red-600 px-4 py-3 font-bold">عرض الطلب</Link><Link href="/store/games" className="flex-1 rounded-2xl border border-white/10 px-4 py-3 font-bold">العودة للمتجر</Link></div></section>
  return <div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><section className="rounded-3xl border border-white/10 bg-[#090d10] p-5"><div className="flex items-center justify-between"><div><p className="text-sm text-zinc-400">الباقة المختارة</p><h2 className="mt-1 text-2xl font-black">{selected.amount.toLocaleString('en-US')} {selected.unit}</h2></div><p className="text-xl font-bold text-amber-300">{selected.price.toFixed(2)} USD</p></div><label className="mt-8 block text-sm font-bold">معرف اللاعب<input value={playerId} onChange={(event) => setPlayerId(event.target.value)} placeholder="أدخل معرف اللاعب" inputMode="numeric" className="mt-2 h-14 w-full rounded-2xl border border-white/10 bg-black/30 px-4 text-white outline-none focus:border-amber-400" /></label><div className="mt-8"><p className="text-sm font-bold">الكمية</p><div className="mt-2 flex w-fit items-center gap-5 rounded-2xl border border-white/10 bg-black/30 p-2"><button aria-label="تقليل الكمية" onClick={() => setQuantity((value) => Math.max(1, value - 1))} className="grid size-11 place-items-center rounded-xl bg-white/10"><Minus /></button><b className="min-w-8 text-center text-xl">{quantity}</b><button aria-label="زيادة الكمية" onClick={() => setQuantity((value) => Math.min(10, value + 1))} className="grid size-11 place-items-center rounded-xl bg-red-600"><Plus /></button></div></div></section><aside className="h-fit rounded-3xl border border-amber-400/30 bg-[#0d0d0a] p-5"><h2 className="text-xl font-black">ملخص الطلب</h2><div className="mt-5 space-y-4 text-sm"><p className="flex justify-between gap-3"><span className="text-zinc-400">المنتج</span><b>{game.name}</b></p><p className="flex justify-between gap-3"><span className="text-zinc-400">الباقة</span><b>{selected.amount.toLocaleString('en-US')} {selected.unit}</b></p><p className="flex justify-between gap-3"><span className="text-zinc-400">الكمية</span><b>{quantity}</b></p><p className="flex justify-between gap-3"><span className="text-zinc-400">الرصيد الحالي</span><b className="text-emerald-300">{balance.toFixed(2)} USD</b></p><div className="border-t border-white/10 pt-4"><p className="flex justify-between text-lg"><span>الإجمالي</span><b className="text-amber-300">{total.toFixed(2)} USD</b></p></div></div>{error && <p className="mt-4 rounded-2xl border border-red-500/40 bg-red-500/10 p-3 text-sm text-red-200">{error}</p>}<button onClick={purchase} className="mt-6 flex w-full items-center justify-center gap-2 rounded-2xl bg-red-600 px-4 py-4 font-black shadow-[0_0_20px_rgba(255,0,30,.25)]"><WalletCards className="size-5" /> شراء الآن <ChevronLeft className="size-4" /></button></aside></div>
}
