'use client'

import Link from 'next/link'
import { ArrowRight, ChevronLeft, Search, ShoppingBag } from 'lucide-react'
import { useMemo, useState } from 'react'
import { SenoLogo } from '@/components/branding/seno-logo'
import { storeProducts } from '@/lib/store-products'
import { DigitalGiftCard, type DigitalGiftCardData } from '@/components/digital-gift-card'

export type StoreCategory = 'games' | 'apps' | 'gift-cards' | 'services'
type CatalogItem = { slug: string; name: string; description: string; detail: string; imagePosition: string; region?: string; denominations?: string[]; serviceType?: string }
const artwork = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/file_0000000015f4820aad3a7637b56e3f84-WGC1XKchVlp1uO7orecqwKhbJ0S36M.png'
const catalog: Record<StoreCategory, CatalogItem[]> = {
  games: [{ slug: 'pubg-mobile', name: 'PUBG Mobile', description: 'شحن شدات ببجي بسرعة وأمان', detail: 'UC وشحن مباشر', imagePosition: 'object-[50%_65%]' }, { slug: 'free-fire', name: 'Free Fire', description: 'اشحن جواهر فري فاير', detail: 'Diamonds', imagePosition: 'object-[50%_67%]' }, { slug: 'mobile-legends', name: 'Mobile Legends', description: 'شحن الماسات داخل اللعبة', detail: 'Diamonds', imagePosition: 'object-[50%_72%]' }, { slug: 'call-of-duty-mobile', name: 'Call of Duty Mobile', description: 'نقاط CP لحسابك', detail: 'CP', imagePosition: 'object-[50%_58%]' }],
  apps: [{ slug: 'sahra-chat', name: 'Sahra Chat', description: 'اشحن عملاتك داخل التطبيق', detail: 'Masa', imagePosition: 'object-[50%_76%]' }, { slug: 'tiktok', name: 'TikTok', description: 'شحن عملات تيك توك', detail: 'Coins', imagePosition: 'object-[50%_42%]' }, { slug: 'bigo-live', name: 'Bigo Live', description: 'شحن رصيد البث المباشر', detail: 'Diamonds', imagePosition: 'object-[50%_48%]' }],
  'gift-cards': [{ slug: 'google-play', name: 'Google Play', description: 'بطاقات Google Play الرقمية', detail: 'بطاقات رقمية', imagePosition: 'object-center' }, { slug: 'apple-gift-card', name: 'Apple Gift Card', description: 'بطاقات App Store وApple', detail: 'Digital Card', imagePosition: 'object-center' }, { slug: 'playstation', name: 'PlayStation', description: 'بطاقات شحن بلايستيشن', detail: 'PSN Card', imagePosition: 'object-center' }, { slug: 'steam', name: 'Steam', description: 'بطاقات ألعاب Steam', detail: 'Steam Wallet', imagePosition: 'object-center' }],
  services: [{ slug: 'digital-services', name: 'خدمات رقمية', description: 'خدمات رقمية متنوعة من SENO STORE', detail: 'خدمات رقمية', imagePosition: 'object-[50%_86%]' }],
}
const meta: Record<StoreCategory, { title: string; subtitle: string; search: string }> = { games: { title: 'شحن الألعاب', subtitle: 'اشحن ألعابك المفضلة بسرعة وأمان', search: 'ابحث عن اللعبة...' }, apps: { title: 'شحن التطبيقات', subtitle: 'اشحن تطبيقاتك وخدماتك الرقمية بسهولة', search: 'ابحث عن التطبيق...' }, 'gift-cards': { title: 'البطاقات الرقمية', subtitle: 'اختر العلامة والقيمة المناسبة واستلم بطاقتك رقميًا بأمان', search: 'ابحث عن بطاقة...' }, services: { title: 'خدمات أخرى', subtitle: 'خدمات رقمية متنوعة', search: 'ابحث عن خدمة...' } }

function StandardCard({ item, available }: { item: CatalogItem; available: boolean }) { return <article className="overflow-hidden rounded-3xl border border-white/10 bg-[#090d10]" dir="rtl"><div className="relative h-40 overflow-hidden bg-zinc-900"><img src={artwork} alt={item.name} className={`size-full object-cover opacity-80 ${item.imagePosition}`} /><div className="absolute inset-0 bg-gradient-to-t from-[#090d10] to-transparent" /></div><div className="p-4"><h2 className="font-black">{item.name}</h2><p className="mt-1 text-sm text-zinc-400">{item.description}</p>{available ? <Link href={`/checkout?product=${item.slug}`} className="mt-4 flex items-center justify-center gap-2 rounded-2xl bg-red-600 px-4 py-3 text-sm font-bold"><ShoppingBag className="size-4" />شراء الآن</Link> : <span className="mt-4 block rounded-2xl border border-red-500/30 px-4 py-3 text-center text-sm font-bold text-red-200">غير متوفر</span>}</div></article> }

export function StoreCategoryPage({ category }: { category: StoreCategory }) {
  const [query, setQuery] = useState('')
  const items = useMemo(() => catalog[category].filter((item) => `${item.name} ${item.description}`.toLowerCase().includes(query.toLowerCase())), [category, query])
  const page = meta[category]
  return <main className="min-h-screen bg-[#050506] pb-32 text-white" dir="rtl"><div className="mx-auto max-w-6xl px-4 sm:px-6"><header className="flex items-center justify-between gap-4 py-6"><Link href="/store" className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.04] px-4 py-3 text-sm text-zinc-200"><ArrowRight className="size-4" />العودة إلى المتجر</Link><SenoLogo className="w-36" /></header><nav className="mb-6 flex gap-2 text-sm"><Link href="/store" className="text-zinc-400">المتجر</Link><span className="text-zinc-600">/</span><span className="text-amber-300">{page.title}</span></nav><section className="rounded-3xl border border-red-600/70 bg-gradient-to-l from-red-950/70 via-[#0b1014] to-black p-6 shadow-[0_0_28px_rgba(255,0,30,.13)] sm:p-10"><p className="text-sm text-amber-300">{category === 'gift-cards' ? 'بطاقات رقمية موثوقة' : 'Seno Store'}</p><h1 className="mt-2 text-3xl font-black sm:text-5xl">{page.title}</h1><p className="mt-3 text-zinc-300 sm:text-lg">{page.subtitle}</p></section><div className="my-6 flex h-14 items-center gap-3 rounded-2xl border border-white/15 bg-white/[0.04] px-4"><Search className="size-5 text-amber-300" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={page.search} className="min-w-0 flex-1 bg-transparent text-white outline-none placeholder:text-zinc-500" /></div>{category === 'gift-cards' && <div className="mb-6 rounded-2xl border border-amber-400/20 bg-amber-400/[.06] p-4 text-sm text-amber-100">اختر البطاقة والقيمة المناسبة. الأسعار والتوفر والمنطقة تُدار من النظام، ولا يمكن تعديلها من العميل.</div>}{items.length ? <section className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{items.flatMap((item) => { const product = storeProducts.find((entry) => entry.slug === item.slug); if (category === 'gift-cards' && product?.digitalCardPackages) return product.digitalCardPackages.map((card) => <DigitalGiftCard key={card.id} productSlug={item.slug} card={{ ...card, brand: item.name, imageUrl: product.imageUrl ?? '/images/category-gift-cards.png' }} />); return [<StandardCard key={item.slug} item={item} available={product?.isAvailable ?? false} />] })}</section> : <div className="rounded-3xl border border-white/10 p-10 text-center text-zinc-400">لا توجد نتائج مطابقة.</div>}</div></main>
}

export { meta as labels }
