'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { readGameOrders, type GameOrder } from '@/lib/data'
import { ClipboardList, Clock3, CheckCircle2, ChevronLeft, Search, Wallet, RotateCcw } from 'lucide-react'
import { SenoLogo } from '@/components/branding/seno-logo'
import { SidebarTrigger } from '@/components/global-sidebar'

const image = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/file_0000000015f4820aad3a7637b56e3f84-WGC1XKchVlp1uO7orecqwKhbJ0S36M.png'
type Status = 'pending' | 'processing' | 'completed' | 'failed' | 'cancelled'
type Order = { id: string; product: string; package: string; playerId?: string; date: string; amount: number; delivery: 'api' | 'manual'; status: Status; image: string; code?: boolean }

const orders: Order[] = [
  { id: 'SNO-10482', product: 'PUBG Mobile', package: '660 UC', playerId: '512345678', date: '19 سبتمبر 2026 - 10:32 م', amount: 680, delivery: 'api', status: 'completed', image, code: false },
  { id: 'SNO-10471', product: 'Free Fire', package: '100 Diamonds', date: '18 سبتمبر 2026 - 08:15 م', amount: 110, delivery: 'api', status: 'processing', image },
  { id: 'SNO-10455', product: 'Sahra Chat', package: '6,000 Masa', date: '17 سبتمبر 2026 - 04:40 م', amount: 240, delivery: 'manual', status: 'pending', image },
  { id: 'SNO-10421', product: 'Google Play', package: '$10 Gift Card', date: '15 سبتمبر 2026 - 12:10 م', amount: 550, delivery: 'manual', status: 'failed', image, code: true },
]
const statusLabels: Record<Status, string> = { pending: 'قيد الانتظار', processing: 'قيد التنفيذ', completed: 'مكتملة', failed: 'فاشلة', cancelled: 'ملغاة' }
const statusClasses: Record<Status, string> = { pending: 'border-amber-400/40 bg-amber-400/10 text-amber-300', processing: 'border-amber-400/40 bg-amber-400/10 text-amber-300', completed: 'border-emerald-400/40 bg-emerald-400/10 text-emerald-300', failed: 'border-red-400/40 bg-red-400/10 text-red-300', cancelled: 'border-red-400/40 bg-red-400/10 text-red-300' }

function Header() { return <header className="flex items-center justify-between gap-3 py-4" dir="ltr"><Link href="/" className="grid size-10 place-items-center rounded-xl border border-white/10 bg-white/[.05] text-white" aria-label="رجوع"><ChevronLeft className="rotate-180" /></Link><SenoLogo className="w-32" /><div className="flex items-center gap-2"><div className="hidden items-center gap-1 rounded-full border border-red-500/60 px-3 py-2 text-xs sm:flex"><Wallet className="size-4 text-amber-300" />500.00 EGP</div><SidebarTrigger /></div></header> }
function StatusBadge({ status }: { status: Status }) { return <span className={`shrink-0 rounded-full border px-2.5 py-1 text-[11px] font-bold ${statusClasses[status]}`}>{statusLabels[status]}</span> }
function Stats({ allOrders }: { allOrders: Order[] }) { const stats = [['إجمالي الطلبات', allOrders.length, ClipboardList], ['مكتملة', allOrders.filter((order) => order.status === 'completed').length, CheckCircle2], ['قيد التنفيذ', allOrders.filter((order) => order.status === 'processing').length, Clock3], ['قيد الانتظار', allOrders.filter((order) => order.status === 'pending').length, Clock3]] as const; return <div className="grid grid-cols-2 gap-2.5">{stats.map(([label, value, Icon]) => <div key={label} className="rounded-2xl border border-white/10 bg-[#0b1014] p-3"><div className="flex items-center justify-between"><span className="text-xs text-zinc-400">{label}</span><Icon className="size-4 text-amber-300" /></div><strong className="mt-1 block text-xl font-black">{value}</strong></div>)}</div> }
function OrderRow({ order }: { order: Order }) { return <article className="rounded-2xl border border-white/10 bg-[#0b0f12] p-3.5 transition hover:border-amber-400/40"><div className="flex items-start gap-3"><img src={order.image} alt="" aria-hidden="true" className="size-12 shrink-0 rounded-xl border border-white/10 object-cover object-[50%_65%]" /><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="text-[11px] text-zinc-500">#{order.id}</p><h2 className="mt-0.5 truncate text-sm font-black text-white">{order.product}</h2></div><StatusBadge status={order.status} /></div><p className="mt-1 text-xs text-zinc-300">{order.package}</p><div className="mt-2 flex items-center justify-between gap-2 text-[11px] text-zinc-500"><span>{order.date}</span><b className="text-sm text-amber-300">{order.amount.toFixed(2)} EGP</b></div></div></div><div className="mt-3 flex items-center justify-end border-t border-white/10 pt-2.5"><Link href={`/orders/${order.id}`} className="rounded-lg border border-amber-400/60 px-3 py-1.5 text-xs font-bold text-amber-300">عرض التفاصيل</Link></div></article> }

export default function OrdersPage() { const [filter, setFilter] = useState<'all' | Status>('all'); const [query, setQuery] = useState(''); const [gameOrders, setGameOrders] = useState<GameOrder[]>([]); useEffect(() => setGameOrders(readGameOrders()), []); const allOrders: Order[] = [...gameOrders.map((order) => ({ id: order.id, product: order.gameName, package: `${order.package} × ${order.quantity}`, playerId: order.playerId, date: order.createdAt, amount: order.total, delivery: 'api' as const, status: 'processing' as Status, image })), ...orders]; const filtered = useMemo(() => { const term = query.trim().toLowerCase(); return allOrders.filter((order) => (filter === 'all' || order.status === filter) && `${order.id} ${order.product} ${order.package} ${order.playerId ?? ''}`.toLowerCase().includes(term)); }, [allOrders, filter, query]); return <main className="min-h-screen bg-[#050506] pb-32 text-white" dir="rtl"><div className="mx-auto max-w-5xl px-5 sm:px-6"><Header /><div className="space-y-4 pb-8"><div><h1 className="text-2xl font-black">طلباتي</h1><p className="mt-1 text-sm text-zinc-400">تابع جميع طلباتك وعمليات الشحن</p></div><Stats allOrders={allOrders} /><div className="-mx-1 flex gap-2 overflow-x-auto px-1 pb-1">{[['all', 'الكل'], ['completed', 'مكتملة'], ['processing', 'قيد التنفيذ'], ['pending', 'قيد الانتظار'], ['failed', 'قيد المراجعة'], ['cancelled', 'ملغاة']].map(([value, label]) => <button key={value} type="button" onClick={() => setFilter(value as typeof filter)} className={`shrink-0 rounded-full border px-3.5 py-2 text-xs font-bold transition ${filter === value ? 'border-red-500 bg-red-600 text-white' : 'border-white/10 bg-[#0b1014] text-zinc-300'}`}>{label}</button>)}</div><label className="flex h-12 items-center gap-3 rounded-xl border border-white/10 bg-[#0b1014] px-3.5"><Search className="size-4 shrink-0 text-zinc-500" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ابحث برقم الطلب أو اسم المنتج..." className="w-full bg-transparent text-sm text-white outline-none placeholder:text-zinc-500" /></label><div className="flex items-center justify-between"><h2 className="text-base font-black">الطلبات ({filtered.length})</h2>{(filter !== 'all' || query) && <button type="button" onClick={() => { setFilter('all'); setQuery('') }} className="flex items-center gap-1 text-xs text-amber-300"><RotateCcw className="size-3" />إعادة ضبط</button>}</div>{filtered.length > 0 ? <div className="grid gap-2.5">{filtered.map((order) => <OrderRow key={order.id} order={order} />)}</div> : <div className="rounded-2xl border border-dashed border-white/15 bg-[#0b1014] px-5 py-12 text-center"><p className="font-bold">{query ? 'لم يتم العثور على طلبات مطابقة' : 'لا توجد طلبات حتى الآن'}</p><p className="mt-1 text-sm text-zinc-500">ستظهر طلباتك هنا بعد إتمام عملية الشراء</p></div>}</div></div></main> }
