'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { readGameOrders, type GameOrder } from '@/lib/game-data'
import { Bell, ClipboardList, CircleUserRound, Clock3, FileText, Gamepad2, Home, Search, Store, Wallet, CheckCircle2, ChevronLeft, RotateCcw } from 'lucide-react'
import { SenoLogo } from '@/components/branding/seno-logo'

const image = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/file_0000000015f4820aad3a7637b56e3f84-WGC1XKchVlp1uO7orecqwKhbJ0S36M.png'
type Status = 'pending' | 'processing' | 'completed' | 'failed' | 'cancelled'
type Order = { id: string; product: string; package: string; playerId?: string; date: string; amount: number; delivery: 'api' | 'manual'; status: Status; image: string; code?: boolean }
const orders: Order[] = [
  { id: 'SNO-10482', product: 'PUBG Mobile', package: '660 UC', playerId: '512345678', date: '19 سبتمبر 2026 - 10:32 م', amount: 680, delivery: 'api', status: 'completed', image, code: false },
  { id: 'SNO-10471', product: 'Free Fire', package: '100 Diamonds', date: '18 سبتمبر 2026 - 08:15 م', amount: 110, delivery: 'api', status: 'processing', image },
  { id: 'SNO-10455', product: 'Sahra Chat', package: '6,000 Masa', date: '17 سبتمبر 2026 - 04:40 م', amount: 240, delivery: 'manual', status: 'pending', image },
  { id: 'SNO-10421', product: 'Google Play', package: '$10 Gift Card', date: '15 سبتمبر 2026 - 12:10 م', amount: 550, delivery: 'manual', status: 'failed', image, code: true },
]
const statusLabels: Record<Status, string> = { pending: 'قيد الانتظار', processing: 'قيد المعالجة', completed: 'مكتملة', failed: 'فاشلة', cancelled: 'ملغاة' }
const statusClasses: Record<Status, string> = { pending: 'border-amber-400/50 bg-amber-400/10 text-amber-300', processing: 'border-amber-400/50 bg-amber-400/10 text-amber-300', completed: 'border-emerald-400/50 bg-emerald-400/10 text-emerald-300', failed: 'border-red-400/50 bg-red-400/10 text-red-300', cancelled: 'border-red-400/50 bg-red-400/10 text-red-300' }
const statusImageGlow: Record<Status, string> = { pending: 'border-amber-400 shadow-[0_0_20px_rgba(251,191,36,.55)]', processing: 'border-amber-400 shadow-[0_0_20px_rgba(251,191,36,.55)]', completed: 'border-emerald-400 shadow-[0_0_20px_rgba(16,185,129,.55)]', failed: 'border-red-500 shadow-[0_0_20px_rgba(239,68,68,.65)]', cancelled: 'border-red-500 shadow-[0_0_20px_rgba(239,68,68,.65)]' }
function Header() { return <header className="flex items-center justify-between gap-3 py-5 sm:py-8" dir="ltr"><Link href="/" className="grid size-11 place-items-center rounded-2xl border border-white/10 bg-white/[.06] text-white" aria-label="رجوع"><ChevronLeft className="rotate-180" /></Link><SenoLogo className="w-40" /><div className="flex items-center gap-2 sm:gap-5"><div className="hidden rounded-full border border-red-500/60 px-5 py-3 text-lg sm:block"><Wallet className="mr-2 inline text-amber-300" />500.00 EGP</div><button aria-label="الإشعارات" className="relative p-2 text-amber-300"><Bell /><i className="absolute right-1 top-1 size-2.5 rounded-full bg-red-500" /></button><button aria-label="الحساب" className="grid size-10 place-items-center rounded-full border border-amber-400 bg-zinc-900"><CircleUserRound className="text-amber-200" /></button></div></header> }
function SectionTitle({ children }: { children: React.ReactNode }) { return <h2 className="mb-4 flex items-center gap-2 text-xl font-black sm:text-2xl">{children}</h2> }
function StatusBadge({ status }: { status: Status }) { return <span className={`rounded-full border px-3 py-1 text-xs font-bold ${statusClasses[status]}`}>{statusLabels[status]}</span> }
function Stats() { return <div className="flex gap-3 overflow-x-auto pb-1">{[['إجمالي الطلبات','24',ClipboardList],['مكتملة','18',CheckCircle2],['قيد التنفيذ','4',Clock3],['قيد المراجعة','2',Clock3]].map(([label,value,Icon]) => <div key={label as string} className="min-w-36 flex-1 rounded-2xl border border-white/10 bg-[#0b1014] p-4"><Icon className="mb-2 text-amber-300" /><p className="text-sm text-zinc-400">{label as string}</p><strong className="text-2xl">{value as string}</strong></div>)}</div> }
function OrderCard({ order }: { order: Order }) { return <article className="rounded-3xl border border-white/10 bg-[#090d10] p-4 shadow-[0_0_22px_rgba(255,0,30,.06)] sm:p-5"><div className="flex gap-4"><img src={order.image} alt={order.product} className={`size-24 shrink-0 rounded-2xl border-2 object-cover object-[50%_65%] transition-shadow duration-300 sm:size-32 ${statusImageGlow[order.status]}`} /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><span className="text-xs text-zinc-500">#{order.id}</span><StatusBadge status={order.status} /></div><h3 className="mt-2 text-lg font-black">{order.product}</h3><p className="text-sm text-zinc-300">{order.package}</p><p className="mt-2 text-xs text-zinc-500">{order.date}</p></div></div><div className="mt-4 grid grid-cols-2 gap-3 border-t border-white/10 pt-4 text-sm"><div><span className="block text-zinc-500">المبلغ</span><b className="text-amber-300">{order.amount.toFixed(2)} EGP</b></div><div><span className="block text-zinc-500">التنفيذ</span><b>{order.delivery === 'api' ? 'شحن تلقائي' : 'تنفيذ يدوي'}</b></div></div><div className="mt-4 flex items-center justify-between gap-3"><span className="text-xs text-zinc-400">{order.status === 'completed' ? 'تم الشحن بنجاح' : order.delivery === 'api' ? 'متوقع خلال دقائق' : 'جاري تنفيذ الطلب بواسطة فريق الدعم'}</span><Link href={`/orders/${order.id}`} className="rounded-full border border-amber-400 px-4 py-2 text-sm font-bold text-amber-300">عرض التفاصيل</Link></div></article> }
export default function OrdersPage() { const [filter, setFilter] = useState<'all' | Status>('all'); const [query, setQuery] = useState(''); const [gameOrders, setGameOrders] = useState<GameOrder[]>([]); useEffect(() => setGameOrders(readGameOrders()), []); const allOrders: Order[] = [...gameOrders.map((order) => ({ id: order.id, product: order.gameName, package: `${order.package} × ${order.quantity}`, playerId: order.playerId, date: order.createdAt, amount: order.total, delivery: 'api' as const, status: 'processing' as Status, image })), ...orders]; const filtered = useMemo(() => allOrders.filter((order) => (filter === 'all' || order.status === filter) && `${order.id} ${order.product} ${order.playerId ?? ''}`.toLowerCase().includes(query.toLowerCase())), [filter, query]); return <main className="min-h-screen bg-[#050506] pb-32 text-white" dir="rtl"><div className="mx-auto max-w-6xl px-4 sm:px-6"><Header /><div className="flex flex-col gap-6 pb-8"><div><h1 className="text-3xl font-black sm:text-4xl">طلباتي</h1><p className="mt-2 text-zinc-400">تابع جميع طلباتك وعمليات الشحن</p></div><Stats /><div className="flex gap-2 overflow-x-auto pb-1">{[['all','الكل'],['pending','قيد الانتظار'],['processing','قيد المعالجة'],['completed','مكتملة'],['failed','فاشلة'],['cancelled','ملغاة']].map(([value,label]) => <button key={value} onClick={() => setFilter(value as typeof filter)} className={`shrink-0 rounded-full border px-4 py-2 text-sm font-bold ${filter === value ? 'border-red-500 bg-red-600 text-white shadow-[0_0_18px_rgba(255,0,30,.35)]' : 'border-white/10 bg-[#0b1014] text-zinc-300'}`}>{label}</button>)}</div><label className="flex items-center gap-3 rounded-2xl border border-white/10 bg-[#0b1014] px-4 py-3"><Search className="text-zinc-500" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="ابحث برقم الطلب أو اسم المنتج..." className="w-full bg-transparent text-white outline-none placeholder:text-zinc-500" /></label><div className="grid gap-4 lg:grid-cols-2">{filtered.map((order) => <OrderCard key={order.id} order={order} />)}</div>{filtered.length === 0 && <div className="rounded-3xl border border-white/10 bg-[#090d10] px-6 py-16 text-center"><Gamepad2 className="mx-auto size-12 text-amber-300" /><h2 className="mt-4 text-xl font-black">لا توجد طلبات حتى الآن</h2><p className="mt-2 text-zinc-400">ابدأ بشراء أول منتج من متجر Seno Store.</p><Link href="/store" className="mt-5 inline-flex rounded-full bg-red-600 px-6 py-3 font-bold">تصفح المتجر</Link></div>}</div></div></main> }
