'use client'

import { useState, type ReactNode } from 'react'
import { usePathname } from 'next/navigation'
import { AlertCircle, Bell, Check, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, LogOut, Menu, PanelRightClose, PanelRightOpen, Settings, UserRound, X } from 'lucide-react'
import { toast } from 'sonner'
import { SenoLogo } from '@/components/branding/seno-logo'
import { cn } from '@/lib/utils'
import { adminNavigation, adminNotifications, adminProfile, type AdminNavGroup, type AdminNavItem } from './admin-navigation'

export function AdminNavItem({ item, collapsed, onNavigate }: { item: AdminNavItem; collapsed: boolean; onNavigate?: () => void }) {
  const pathname = usePathname()
  const active = pathname === item.href
  const Icon = item.icon
  const content = <><Icon className="size-[17px] shrink-0" aria-hidden="true" /><span className={cn('truncate transition-opacity', collapsed && 'lg:w-0 lg:opacity-0')}>{item.label}</span>{item.disabled && !collapsed && <span className="mr-auto rounded-full border border-white/10 px-1.5 py-0.5 text-[9px] text-white/35">قريباً</span>}</>
  if (item.disabled) return <button type="button" onClick={() => toast.info('سيتم تفعيل هذه الصفحة في مرحلة لاحقة.')} className={cn('group flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-right text-[12px] text-white/45 transition hover:bg-white/[.04] hover:text-white/70', collapsed && 'lg:justify-center lg:px-0')} title={collapsed ? item.label : undefined}>{content}</button>
  return <a href={item.href} onClick={onNavigate} className={cn('group flex items-center gap-3 rounded-xl px-3 py-2.5 text-right text-[12px] transition', active ? 'bg-[#f5c542] font-bold text-[#090909] shadow-[0_8px_20px_rgba(245,197,66,.12)]' : 'text-white/60 hover:bg-white/[.05] hover:text-white', collapsed && 'lg:justify-center lg:px-0')} title={collapsed ? item.label : undefined}>{content}</a>
}

export function AdminNavGroup({ group, collapsed, onNavigate }: { group: AdminNavGroup; collapsed: boolean; onNavigate?: () => void }) {
  const pathname = usePathname()
  const hasActive = group.items.some(item => pathname === item.href)
  const [open, setOpen] = useState(hasActive || group.label === 'الرئيسية')
  return <div className="flex flex-col gap-1"><button type="button" onClick={() => setOpen(value => !value)} className={cn('flex items-center justify-between px-3 pb-1 pt-3 text-[10px] font-bold tracking-wide text-white/30', collapsed && 'lg:justify-center lg:px-0')}><span className={cn(collapsed && 'lg:hidden')}>{group.label}</span><ChevronDown className={cn('size-3 transition-transform', !open && '-rotate-90', collapsed && 'lg:hidden')} aria-hidden="true" /></button>{open && <div className="flex flex-col gap-0.5">{group.items.map(item => <AdminNavItem key={item.href} item={item} collapsed={collapsed} onNavigate={onNavigate} />)}</div>}</div>
}

export function AdminSidebar({ mobile = false, collapsed = false, onClose }: { mobile?: boolean; collapsed?: boolean; onClose?: () => void }) {
  return <aside className={cn('flex h-full flex-col border-l border-white/[.08] bg-[#090b0d]', mobile ? 'w-[min(86vw,320px)]' : 'w-[278px] shrink-0', !mobile && collapsed && 'lg:w-[78px]')}>
    <div className="flex h-[76px] items-center justify-between border-b border-white/[.08] px-5"><SenoLogo className={cn('transition-all', collapsed && 'lg:w-12')} />{mobile && <button type="button" onClick={onClose} className="rounded-lg p-2 text-white/50 hover:bg-white/5 hover:text-white" aria-label="إغلاق القائمة"><X className="size-5" /></button>}</div>
    <div className={cn('border-b border-white/[.08] px-5 py-4', collapsed && 'lg:px-3')}><div className={cn('text-[10px] font-bold uppercase tracking-[.22em] text-[#f5c542]', collapsed && 'lg:hidden')}>SENO STORE</div><div className={cn('mt-1 text-sm font-bold text-white', collapsed && 'lg:hidden')}>مركز التحكم الإداري</div><div className={cn('mt-3 h-1 w-10 rounded-full bg-[#f5c542]', collapsed && 'lg:mx-auto')} /></div>
    <nav className="min-h-0 flex-1 overflow-y-auto px-3 pb-8" aria-label="التنقل الإداري">{adminNavigation.map(group => <AdminNavGroup key={group.label} group={group} collapsed={collapsed} onNavigate={onClose} />)}</nav>
  </aside>
}

export function AdminProfileMenu() {
  const [open, setOpen] = useState(false)
  return <div className="relative"><button type="button" onClick={() => setOpen(value => !value)} className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/[.03] px-2.5 py-1.5 text-right hover:bg-white/[.06]" aria-expanded={open}><span className="hidden text-right sm:block"><span className="block text-xs font-bold text-white">{adminProfile.name}</span><span className="block text-[10px] text-white/40">{adminProfile.role}</span></span><span className="grid size-8 place-items-center rounded-lg bg-[#f5c542] text-sm font-black text-[#090909]">أ</span><ChevronDown className="size-3 text-white/40" /></button>{open && <div className="absolute left-0 top-[calc(100%+10px)] z-50 w-48 rounded-2xl border border-white/10 bg-[#111518] p-2 shadow-2xl"><div className="border-b border-white/10 px-3 pb-3 pt-2"><p className="text-sm font-bold text-white">{adminProfile.name}</p><p className="text-[11px] text-white/40">{adminProfile.role}</p></div>{[['الملف الشخصي', UserRound], ['الإعدادات', Settings], ['تسجيل الخروج', LogOut]].map(([label, Icon]) => <button key={String(label)} type="button" onClick={() => toast.info('هذه الميزة ستكون متاحة لاحقاً.')} className="flex w-full items-center gap-2 rounded-xl px-3 py-2.5 text-right text-xs text-white/65 hover:bg-white/5 hover:text-white"><Icon className="size-4" />{label as string}</button>)}</div>}</div>
}

export function AdminNotifications() {
  const [open, setOpen] = useState(false)
  return <div className="relative"><button type="button" onClick={() => setOpen(value => !value)} className="relative rounded-xl border border-white/10 bg-white/[.03] p-2.5 text-white/65 hover:bg-white/[.06] hover:text-white" aria-label="الإشعارات" aria-expanded={open}><Bell className="size-[18px]" /><span className="absolute right-1.5 top-1.5 size-1.5 rounded-full bg-[#f5c542]" /></button>{open && <div className="absolute left-0 top-[calc(100%+10px)] z-50 w-[min(90vw,340px)] rounded-2xl border border-white/10 bg-[#111518] p-3 shadow-2xl"><div className="flex items-center justify-between border-b border-white/10 px-2 pb-3"><div><h2 className="text-sm font-bold text-white">الإشعارات</h2><p className="mt-1 text-[10px] text-white/35">آخر التنبيهات الإدارية</p></div><span className="rounded-full bg-[#f5c542]/10 px-2 py-1 text-[10px] font-bold text-[#f5c542]">4 جديدة</span></div><div className="flex flex-col gap-1 pt-2">{adminNotifications.map(notification => <button type="button" key={notification.title} onClick={() => setOpen(false)} className="flex gap-3 rounded-xl p-2.5 text-right hover:bg-white/5"><span className={cn('mt-1 size-2 shrink-0 rounded-full', notification.tone === 'gold' && 'bg-[#f5c542]', notification.tone === 'green' && 'bg-[#45e0b2]', notification.tone === 'red' && 'bg-[#e50914]', notification.tone === 'muted' && 'bg-white/25')} /><span><span className="block text-xs font-semibold text-white/85">{notification.title}</span><span className="mt-1 block text-[10px] text-white/35">{notification.detail}</span></span></button>)}</div></div>}</div>
}

export function AdminHeader({ onMenu, collapsed, onToggleSidebar }: { onMenu: () => void; collapsed: boolean; onToggleSidebar: () => void }) {
  return <header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-white/[.08] bg-[#07090b]/90 px-4 backdrop-blur-xl sm:px-6 lg:px-8"><div className="flex items-center gap-2"><button type="button" onClick={onMenu} className="rounded-xl border border-white/10 p-2.5 text-white/60 hover:bg-white/5 hover:text-white lg:hidden" aria-label="فتح القائمة"><Menu className="size-[18px]" /></button><button type="button" onClick={onToggleSidebar} className="hidden rounded-xl border border-white/10 p-2.5 text-white/50 hover:bg-white/5 hover:text-white lg:block" aria-label={collapsed ? 'توسيع القائمة' : 'تصغير القائمة'}>{collapsed ? <PanelRightOpen className="size-[17px]" /> : <PanelRightClose className="size-[17px]" />}</button><div className="hidden items-center gap-2 text-xs text-white/40 sm:flex"><span>الإدارة</span><ChevronLeft className="size-3" /><span className="text-white/75">مركز التحكم</span></div></div><div className="flex items-center gap-2"><AdminNotifications /><AdminProfileMenu /></div></header>
}

export function AdminBreadcrumbs({ items = [{ label: 'الرئيسية', href: '/admin' }, { label: 'مركز التحكم' }] }: { items?: { label: string; href?: string }[] }) {
  return <nav aria-label="مسار التنقل" className="flex flex-wrap items-center gap-2 text-xs text-white/40">{items.map((item, index) => <span key={`${item.label}-${index}`} className="flex items-center gap-2">{item.href ? <a href={item.href} className="hover:text-[#f5c542]">{item.label}</a> : <span className="text-white/75">{item.label}</span>}{index < items.length - 1 && <ChevronLeft className="size-3 text-white/25" aria-hidden="true" />}</span>)}</nav>
}

export function AdminPageContainer({ children, className }: { children: ReactNode; className?: string }) { return <div className={cn('mx-auto w-full max-w-[1500px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8', className)}>{children}</div> }
export function AdminPageHeader({ title, description, breadcrumbs, actions }: { title: string; description?: string; breadcrumbs?: { label: string; href?: string }[]; actions?: ReactNode }) { return <div className="mb-8 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><AdminBreadcrumbs items={breadcrumbs} /><h1 className="mt-4 text-2xl font-black tracking-tight text-white sm:text-3xl">{title}</h1>{description && <p className="mt-2 max-w-2xl text-sm leading-7 text-white/45">{description}</p>}</div>{actions && <div className="flex shrink-0 items-center gap-2">{actions}</div>}</div> }
export function AdminCard({ children, className }: { children: ReactNode; className?: string }) { return <section className={cn('rounded-2xl border border-white/[.09] bg-[#0b0f12] shadow-[0_18px_50px_rgba(0,0,0,.12)]', className)}>{children}</section> }
export function AdminSection({ title, description, children, className }: { title?: string; description?: string; children: ReactNode; className?: string }) { return <section className={cn('flex flex-col gap-4', className)}>{(title || description) && <div><h2 className="text-lg font-bold text-white">{title}</h2>{description && <p className="mt-1 text-xs text-white/40">{description}</p>}</div>}{children}</section> }
export function AdminToolbar({ children }: { children: ReactNode }) { return <div className="flex flex-wrap items-center gap-3 rounded-2xl border border-white/[.08] bg-[#0b0f12] p-3">{children}</div> }
export function AdminTableContainer({ children }: { children: ReactNode }) { return <div className="overflow-x-auto rounded-2xl border border-white/[.08] bg-[#0b0f12]">{children}</div> }
export function AdminFormSection({ title, description, children }: { title: string; description?: string; children: ReactNode }) { return <AdminCard><div className="border-b border-white/[.08] px-5 py-4"><h2 className="font-bold text-white">{title}</h2>{description && <p className="mt-1 text-xs text-white/40">{description}</p>}</div><div className="p-5">{children}</div></AdminCard> }

export function AdminLoadingState({ message = 'جاري التحميل...' }: { message?: string }) { return <div className="flex min-h-56 items-center justify-center gap-3 text-sm text-white/50" role="status"><span className="size-4 animate-spin rounded-full border-2 border-[#f5c542]/25 border-t-[#f5c542]" />{message}</div> }
export function AdminEmptyState({ title = 'لا توجد بيانات حالياً', description, action }: { title?: string; description?: string; action?: ReactNode }) { return <div className="flex min-h-56 flex-col items-center justify-center px-5 text-center"><span className="grid size-12 place-items-center rounded-2xl border border-white/10 bg-white/[.03] text-white/35"><CircleHelp className="size-5" /></span><h2 className="mt-4 font-bold text-white">{title}</h2>{description && <p className="mt-2 max-w-sm text-xs leading-6 text-white/40">{description}</p>}{action && <div className="mt-4">{action}</div>}</div> }
export function AdminErrorState({ title = 'حدث خطأ أثناء تحميل البيانات', description = 'تعذر إتمام العملية، حاول مرة أخرى.', onRetry }: { title?: string; description?: string; onRetry?: () => void }) { return <div className="flex min-h-56 flex-col items-center justify-center px-5 text-center" role="alert"><span className="grid size-12 place-items-center rounded-2xl border border-[#e50914]/20 bg-[#e50914]/10 text-[#e50914]"><AlertCircle className="size-5" /></span><h2 className="mt-4 font-bold text-white">{title}</h2><p className="mt-2 max-w-sm text-xs leading-6 text-white/40">{description}</p>{onRetry && <button type="button" onClick={onRetry} className="mt-4 rounded-xl bg-[#e50914] px-4 py-2.5 text-xs font-bold text-white">إعادة المحاولة</button>}</div> }
export function AdminConfirmDialog({ open, title = 'تأكيد الإجراء', description = 'هل أنت متأكد من تنفيذ هذا الإجراء؟', confirmLabel = 'تأكيد', destructive = false, onCancel, onConfirm }: { open: boolean; title?: string; description?: string; confirmLabel?: string; destructive?: boolean; onCancel: () => void; onConfirm: () => void }) { if (!open) return null; return <div className="fixed inset-0 z-[100] grid place-items-center bg-black/70 p-4 backdrop-blur-sm" role="presentation"><div role="dialog" aria-modal="true" aria-labelledby="admin-confirm-title" className="w-full max-w-md rounded-2xl border border-white/10 bg-[#111518] p-6 shadow-2xl"><h2 id="admin-confirm-title" className="text-lg font-bold text-white">{title}</h2><p className="mt-2 text-sm leading-7 text-white/55">{description}</p><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onCancel} className="rounded-xl border border-white/10 px-4 py-2.5 text-xs font-bold text-white/65 hover:bg-white/5">إلغاء</button><button type="button" onClick={onConfirm} className={cn('rounded-xl px-4 py-2.5 text-xs font-bold text-white', destructive ? 'bg-[#e50914] hover:bg-[#c90812]' : 'bg-[#f5c542] text-[#090909] hover:bg-[#ffd55d]')}>{confirmLabel}</button></div></div></div> }

export function AdminShell({ children }: { children: ReactNode }) {
  const [mobileOpen, setMobileOpen] = useState(false)
  const [collapsed, setCollapsed] = useState(false)
  return <div dir="rtl" className="flex min-h-screen bg-[#050505] text-white"><div className="hidden lg:block"><AdminSidebar collapsed={collapsed} /></div>{mobileOpen && <div className="fixed inset-0 z-50 flex lg:hidden"><button type="button" onClick={() => setMobileOpen(false)} className="flex-1 bg-black/70 backdrop-blur-sm" aria-label="إغلاق القائمة" /><div className="h-full"><AdminSidebar mobile onClose={() => setMobileOpen(false)} /></div></div>}<div className="flex min-w-0 flex-1 flex-col"><AdminHeader onMenu={() => setMobileOpen(true)} collapsed={collapsed} onToggleSidebar={() => setCollapsed(value => !value)} /><main className="min-h-0 flex-1 overflow-y-auto">{children}</main></div></div>
}
