'use client'

import { useMemo, useState } from 'react'
import { ImagePlus, Plus, Search, Trash2 } from 'lucide-react'
import { toast } from 'sonner'
import { AdminCard, AdminPageContainer, AdminPageHeader } from '@/components/admin/admin-components'
import { categories } from '@/lib/data/categories'
import { getProducts } from '@/lib/data/products'
import type { Category, CategoryPurpose } from '@/lib/data/types'
import type { HomepageBanner } from '@/lib/data/homepage'

const statusLabels = { active: 'نشط', draft: 'مسودة', scheduled: 'مجدول', inactive: 'غير نشط', archived: 'مؤرشف' } as const
const purposeLabels: Record<CategoryPurpose, string> = { general: 'قسم عام', offers: 'قسم عروض', custom: 'قسم مخصص' }

export function StoreManagementPage({ section }: { section: 'banners' | 'categories' | 'products' | 'packages' }) {
  const titles = { banners: 'إدارة البنرات', categories: 'إدارة الأقسام', products: 'إدارة المنتجات', packages: 'إدارة الباقات' }
  return <AdminPageContainer><AdminPageHeader title={titles[section]} description={section === 'categories' ? 'أنشئ أقسام المتجر وحدد الغرض والصورة الخاصة بكل قسم' : 'إدارة عناصر المتجر مع الحفاظ على مصدر البيانات الموحد'} breadcrumbs={[{ label: 'الرئيسية', href: '/admin' }, { label: 'المتجر' }, { label: titles[section] }]} /><div className="flex flex-col gap-5">{section === 'categories' ? <CategoriesManager /> : section === 'banners' ? <BannersManager /> : <CatalogReferencePage section={section} />}</div></AdminPageContainer>
}

function CategoriesManager() {
  const [items, setItems] = useState<Category[]>(categories)
  const [editing, setEditing] = useState<Category | null>(null)
  const [query, setQuery] = useState('')
  const filtered = items.filter((item) => item.name.includes(query) || item.slug.includes(query))
  const empty: Category = { id: '', name: '', nameEn: '', slug: '', type: 'store', purpose: 'general', description: '', order: items.length + 1, active: true, image: '' }
  const save = (item: Category) => { const next = item.id ? items.map((entry) => entry.id === item.id ? item : entry) : [...items, { ...item, id: `category-${Date.now()}` }]; setItems(next); setEditing(null); toast.success('تم حفظ القسم بنجاح') }
  return <><AdminCard className="p-4 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-bold text-white">الأقسام</h2><p className="mt-1 text-xs text-white/45">الأقسام مصدر للمتجر ويمكن ربطها بالصفحة الرئيسية</p></div><button type="button" onClick={() => setEditing(empty)} className="flex items-center justify-center gap-2 rounded-xl bg-[#f5c542] px-4 py-2.5 text-xs font-black text-black"><Plus className="size-4" />إضافة قسم</button></div><div className="mt-5 flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-3"><Search className="size-4 text-white/40" /><input value={query} onChange={(event) => setQuery(event.target.value)} className="w-full bg-transparent py-3 text-sm text-white outline-none" placeholder="ابحث في الأقسام" /></div><div className="mt-4 grid gap-3 md:grid-cols-2">{filtered.map((item) => <div key={item.id} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[.02] p-3"><img src={item.image || '/images/category-services.png'} alt="" className="size-16 rounded-xl object-cover" /><div className="min-w-0 flex-1"><p className="font-bold text-white">{item.name}</p><p className="mt-1 text-xs text-[#f5c542]">{purposeLabels[item.purpose || 'general']}</p><p className="mt-1 text-[11px] text-white/40">{item.active ? 'نشط' : 'غير نشط'} · ترتيب {item.order}</p></div><button type="button" onClick={() => setEditing(item)} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-white/70">تعديل</button></div>)}</div></AdminCard>{editing && <CategoryForm category={editing} onCancel={() => setEditing(null)} onSave={save} />}</>
}

function CategoryForm({ category, onCancel, onSave }: { category: Category; onCancel: () => void; onSave: (category: Category) => void }) {
  const [form, setForm] = useState(category)
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-4" role="presentation" onClick={onCancel}><div role="dialog" aria-modal="true" aria-label="تحرير القسم" onClick={(event) => event.stopPropagation()} className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-2xl border border-white/10 bg-[#111518] p-5"><h2 className="text-lg font-bold text-white">{form.id ? 'تعديل القسم' : 'إضافة قسم'}</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="اسم القسم بالعربية"><input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Field><Field label="اسم القسم بالإنجليزية"><input value={form.nameEn || ''} onChange={(e) => setForm({ ...form, nameEn: e.target.value })} /></Field><Field label="النوع"><select value={form.purpose || 'general'} onChange={(e) => setForm({ ...form, purpose: e.target.value as CategoryPurpose })}><option value="general">قسم عام</option><option value="offers">قسم عروض</option><option value="custom">قسم مخصص</option></select></Field><Field label="Slug"><input value={form.slug} onChange={(e) => setForm({ ...form, slug: e.target.value })} /></Field><Field label="رابط صورة القسم"><div className="flex gap-2"><input value={form.image || ''} onChange={(e) => setForm({ ...form, image: e.target.value })} placeholder="/images/category-games.png" /><ImagePlus className="mt-2 shrink-0 text-[#f5c542]" /></div></Field><Field label="الترتيب"><input type="number" value={form.order} onChange={(e) => setForm({ ...form, order: Number(e.target.value) })} /></Field><Field label="الحالة"><select value={form.active ? 'active' : 'inactive'} onChange={(e) => setForm({ ...form, active: e.target.value === 'active' })}><option value="active">نشط</option><option value="inactive">غير نشط</option></select></Field><Field label="الوصف"><textarea value={form.description || ''} onChange={(e) => setForm({ ...form, description: e.target.value })} /></Field></div><div className="mt-5 flex gap-2"><button type="button" onClick={onCancel} className="flex-1 rounded-xl border border-white/10 py-3 text-xs text-white/70">إلغاء</button><button type="button" onClick={() => onSave(form)} className="flex-1 rounded-xl bg-[#f5c542] py-3 text-xs font-bold text-black">حفظ</button></div></div></div>
}

function BannersManager() {
  const [banners, setBanners] = useState<HomepageBanner[]>([{ id: 'new-main', nameAr: 'البنر الرئيسي', nameEn: 'Main Homepage Banner', image: '/images/home-banner-new.png', targetType: 'none', placement: 'main_homepage', targetPage: 'homepage', status: 'active', sortOrder: 1, visibility: true, altText: 'البنر الرئيسي', createdAt: '', updatedAt: '' }])
  const [editing, setEditing] = useState<HomepageBanner | null>(null)
  return <><AdminCard className="p-4 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold text-white">البنرات</h2><p className="mt-1 text-xs text-white/45">حدد مكان الظهور والصفحة المستهدفة لكل بنر</p></div><button type="button" onClick={() => setEditing({ id: '', nameAr: '', nameEn: '', image: '/images/home-banner-new.png', targetType: 'none', placement: 'main_homepage', targetPage: 'homepage', status: 'draft', sortOrder: banners.length + 1, visibility: true, altText: '', createdAt: '', updatedAt: '' })} className="rounded-xl bg-[#f5c542] px-4 py-2.5 text-xs font-black text-black"><Plus className="me-2 inline size-4" />إضافة بنر</button></div><div className="mt-5 grid gap-3">{banners.map((banner) => <div key={banner.id} className="flex flex-col gap-3 rounded-2xl border border-white/10 bg-white/[.02] p-3 sm:flex-row sm:items-center"><img src={banner.image} alt={banner.altText} className="h-24 w-full rounded-xl object-cover sm:w-44" /><div className="flex-1"><p className="font-bold text-white">{banner.nameAr}</p><p className="mt-1 text-xs text-[#f5c542]">{banner.placement === 'main_homepage' ? 'البنر الرئيسي للصفحة الرئيسية' : 'بنر ترويجي'}</p><p className="mt-1 text-xs text-white/45">{statusLabels[banner.status]} · {banner.targetPage === 'homepage' ? 'الصفحة الرئيسية' : 'المتجر'}</p></div><button type="button" onClick={() => setEditing(banner)} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-white/70">تعديل</button></div>)}</div></AdminCard>{editing && <BannerForm banner={editing} onCancel={() => setEditing(null)} onSave={(next) => { setBanners((current) => next.id ? current.map((item) => item.id === next.id ? next : item) : [...current, { ...next, id: `banner-${Date.now()}` }]); setEditing(null); toast.success('تم حفظ البنر بنجاح') }} />}</>
}

function BannerForm({ banner, onCancel, onSave }: { banner: HomepageBanner; onCancel: () => void; onSave: (banner: HomepageBanner) => void }) {
  const [form, setForm] = useState(banner)
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-4" role="presentation" onClick={onCancel}><div role="dialog" aria-modal="true" aria-label="تحرير البنر" onClick={(event) => event.stopPropagation()} className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-2xl border border-white/10 bg-[#111518] p-5"><h2 className="text-lg font-bold text-white">{form.id ? 'تعديل البنر' : 'إضافة بنر'}</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="اسم البنر"><input value={form.nameAr} onChange={(e) => setForm({ ...form, nameAr: e.target.value })} /></Field><Field label="رابط الصورة"><input value={form.image} onChange={(e) => setForm({ ...form, image: e.target.value })} /></Field><Field label="مكان الظهور"><select value={form.placement || 'main_homepage'} onChange={(e) => setForm({ ...form, placement: e.target.value as HomepageBanner['placement'] })}><option value="main_homepage">البنر الرئيسي للصفحة الرئيسية</option><option value="homepage_promo">بنر ترويجي للصفحة الرئيسية</option><option value="store">المتجر</option><option value="category">صفحة قسم محدد</option><option value="product">صفحة منتج محدد</option></select></Field><Field label="الصفحة المستهدفة"><select value={form.targetPage || 'homepage'} onChange={(e) => setForm({ ...form, targetPage: e.target.value as HomepageBanner['targetPage'] })}><option value="homepage">الصفحة الرئيسية</option><option value="store">المتجر</option><option value="category">قسم محدد</option><option value="product">منتج محدد</option></select></Field><Field label="معاينة"><img src={form.image} alt={form.altText || 'معاينة البنر'} className="h-28 w-full rounded-xl object-cover" /></Field><Field label="الحالة"><select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as HomepageBanner['status'] })}>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field></div><div className="mt-5 flex gap-2"><button type="button" onClick={onCancel} className="flex-1 rounded-xl border border-white/10 py-3 text-xs text-white/70">إلغاء</button><button type="button" onClick={() => onSave(form)} className="flex-1 rounded-xl bg-[#f5c542] py-3 text-xs font-bold text-black">حفظ</button></div></div></div>
}

function CatalogReferencePage({ section }: { section: 'products' | 'packages' }) { const products = useMemo(() => getProducts(), []); return <AdminCard className="p-6"><h2 className="text-lg font-bold text-white">{section === 'products' ? 'المنتجات' : 'الباقات'}</h2><p className="mt-2 text-sm text-white/45">هذه الصفحة تعرض المصدر الحالي للكتالوج دون إنشاء CRUD جديد.</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{(section === 'products' ? products : products.flatMap((product) => product.digitalCardPackages || []).slice(0, 12)).map((item: any, index) => <div key={item.id || item.slug || index} className="rounded-xl border border-white/10 bg-white/[.02] p-4"><p className="font-bold text-white">{item.name || item.title || `باقة ${index + 1}`}</p><p className="mt-1 text-xs text-white/45">مرجع كتالوج موجود</p></div>)}</div></AdminCard> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-xs font-bold text-white">{label}<div className="mt-2 [&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:border-white/10 [&_input]:bg-white/5 [&_input]:px-3 [&_input]:py-2.5 [&_input]:text-sm [&_input]:text-white [&_input]:outline-none [&_select]:w-full [&_select]:rounded-xl [&_select]:border [&_select]:border-white/10 [&_select]:bg-white/5 [&_select]:px-3 [&_select]:py-2.5 [&_select]:text-sm [&_select]:text-white [&_textarea]:min-h-24 [&_textarea]:w-full [&_textarea]:rounded-xl [&_textarea]:border [&_textarea]:border-white/10 [&_textarea]:bg-white/5 [&_textarea]:p-3 [&_textarea]:text-sm [&_textarea]:text-white">{children}</div></label> }
