'use client'

import { useState } from 'react'
import Image from 'next/image'
import Link from 'next/link'
import { ChevronDown, ChevronLeft, Search, Wallet } from 'lucide-react'
import { SenoLogo } from '@/components/branding/seno-logo'
import { SidebarTrigger } from '@/components/global-sidebar'
import { storeProducts } from '@/lib/store-products'

const artwork = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/file_0000000015f4820aad3a7637b56e3f84-WGC1XKchVlp1uO7orecqwKhbJ0S36M.png'

const banners = [
  { title: 'شحن الألعاب', desc: 'اشحن حساباتك في جميع الألعاب الشهيرة', count: '+50 لعبة', cta: 'استكشف الألعاب', href: '/store/games', image: '/images/category-games.png', alt: 'بنر شحن الألعاب مع يد تحكم وبطاقات ألعاب', tone: 'border-red-600/80' },
  { title: 'شحن التطبيقات', desc: 'اشحن رصيدك في أفضل التطبيقات', count: '+30 تطبيق', cta: 'استكشف التطبيقات', href: '/store/apps', image: '/images/category-apps.png', alt: 'بنر شحن التطبيقات وبطاقات المنصات الرقمية', tone: 'border-amber-500/70' },
  { title: 'البطاقات الرقمية', desc: 'بطاقاتك الرقمية بأمان وسرعة', count: '+100 بطاقة', cta: 'تصفح البطاقات', href: '/store/gift-cards', image: '/images/category-gift-cards.png', alt: 'بنر البطاقات الرقمية وبطاقات الهدايا', tone: 'border-amber-500/70' },
  { title: 'خدمات أخرى', desc: 'خدمات متنوعة تناسب احتياجاتك', count: '+20 خدمة', cta: 'استكشف الخدمات', href: '/store/services', image: '/images/category-services.png', alt: 'بنر الخدمات الرقمية والتحويلات والدفع', tone: 'border-red-600/80' },
]

const productVisuals: Record<string, string> = { 'pubg-mobile': 'object-[50%_65%]', 'free-fire': 'object-[50%_67%]', 'mobile-legends': 'object-[50%_72%]', 'sahra-chat': 'object-[50%_76%]' }
const products = storeProducts.filter((product) => productVisuals[product.slug]).map((product) => ({ ...product, pos: productVisuals[product.slug] }))

function Header({ onMenu }: { onMenu: () => void }) {
  return <header className="flex flex-col gap-6 pt-5 sm:pt-8"><div className="flex items-center justify-between gap-3" dir="ltr"><SenoLogo className="w-40" /><div className="flex items-center gap-2 sm:gap-5"><div className="hidden items-center gap-3 rounded-full border border-red-500/60 bg-white/[0.04] px-5 py-3 text-lg sm:flex"><Wallet className="text-amber-300" />500.00 EGP<ChevronDown className="size-4 text-amber-400" /></div><SidebarTrigger /></div></div><label className="flex h-16 items-center gap-4 rounded-full border border-white/35 bg-white/[0.045] px-6 text-zinc-400" dir="rtl"><input aria-label="البحث" className="min-w-0 flex-1 bg-transparent text-base text-white outline-none placeholder:text-zinc-400 sm:text-lg" placeholder="إبحث عن لعبة أو تطبيق أو بطاقة رقمية..." /><Search className="size-7 shrink-0" /></label></header>
}

function CategoryBanner({ item }: { item: typeof banners[number] }) {
  return <article className={`group relative aspect-[2/1] min-h-44 overflow-hidden rounded-3xl border ${item.tone} bg-black shadow-[0_12px_35px_rgba(0,0,0,.35)]`} dir="rtl"><Image src={item.image} alt={item.alt} fill sizes="(max-width: 640px) calc(100vw - 32px), 960px" className="object-cover object-center transition duration-300 ease-out group-hover:scale-[1.025]" /><div className="absolute inset-0 bg-gradient-to-l from-black/90 via-black/45 to-black/10" /><div className="relative flex h-full flex-col items-start justify-center gap-2 px-5 py-5 sm:px-10"><span className="text-sm font-semibold text-amber-300">{item.count}</span><h2 className="text-2xl font-black text-white drop-shadow-[0_2px_8px_rgba(0,0,0,.8)] sm:text-3xl">{item.title}</h2><p className="max-w-[75%] text-sm text-zinc-200 sm:text-base">{item.desc}</p><Link href={item.href} className="mt-2 rounded-full bg-red-600 px-5 py-2 text-sm font-bold text-white shadow-[0_0_18px_rgba(255,0,30,.35)] transition hover:bg-red-500 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-300">{item.cta}<ChevronLeft className="mr-2 inline size-4" /></Link></div></article>
}

function ProductCard({ product, first }: { product: typeof products[number]; first?: boolean }) {
  return <article className="min-w-[13rem] overflow-hidden rounded-2xl border border-amber-600/60 bg-zinc-950 shadow-[0_0_16px_rgba(255,190,0,.06)] transition hover:-translate-y-1 hover:border-amber-300/80 sm:min-w-0"><div className="relative h-40 overflow-hidden bg-zinc-900"><img src={artwork} alt={product.name} className={`size-full object-cover opacity-90 ${product.pos}`} />{first && <span className="absolute right-2 top-2 rounded-full bg-red-600 px-2 py-1 text-[10px] font-bold">الأكثر طلباً</span>}<span className={`absolute left-2 top-2 rounded-full px-2 py-1 text-[10px] font-black ${product.isAvailable ? 'bg-emerald-600 text-white' : 'bg-red-950 text-red-200'}`}>{product.isAvailable ? 'متاح' : 'غير متوفر'}</span>{product.discountPercentage > 0 && <span className="absolute bottom-2 left-2 rounded-full bg-amber-300 px-2 py-1 text-[10px] font-black text-black">خصم {product.discountPercentage}%</span>}</div><div className="p-3" dir="rtl"><h3 className="font-bold text-white">{product.name}</h3><p className="mt-1 text-sm text-zinc-200">{product.detail}</p><div className="mt-3 flex items-center justify-between gap-2"><div>{product.discountPercentage > 0 && <del className="block text-xs text-zinc-500">{product.oldPrice} EGP</del>}<strong className="text-lg text-amber-300">{product.price} EGP</strong></div>{product.isAvailable ? <Link href={`/checkout?product=${product.slug}`} className="rounded-xl bg-gradient-to-l from-red-600 to-red-500 px-3 py-2 text-sm font-black text-white shadow-[0_0_16px_rgba(239,68,68,.35)] transition hover:from-amber-300 hover:to-amber-400 hover:text-black focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-300">شراء الآن</Link> : <button type="button" disabled className="rounded-xl border border-red-500/50 bg-red-950/40 px-3 py-2 text-sm font-black text-red-200">غير متوفر حاليًا</button>}</div></div></article>
}


export default function StorePage() {
  return <main className="min-h-screen bg-[#050506] pb-28 text-white" dir="rtl"><div className="mx-auto max-w-5xl px-4 sm:px-6"><Header onMenu={() => {}} /><div className="flex flex-col gap-7 py-7"><section className="grid gap-5">{banners.map((item) => <CategoryBanner key={item.title} item={item} />)}</section><section><div className="mb-4 flex items-center justify-between"><h2 className="text-2xl font-black">الأكثر طلباً <span className="text-red-500">♨</span></h2><button className="text-amber-300">عرض الكل <ChevronLeft className="inline size-4" /></button></div><div className="-mx-4 flex gap-3 overflow-x-auto px-4 pb-2 sm:mx-0 sm:grid sm:grid-cols-2 sm:px-0 lg:grid-cols-4">{products.map((product, index) => <ProductCard key={product.name} product={product} first={index === 0} />)}</div></section><section className="relative overflow-hidden rounded-3xl border border-red-600 bg-black px-6 py-6 text-center shadow-[0_0_24px_rgba(255,0,30,.2)]"><Image src="/images/offers-exclusive.png" alt="عروض حصرية من SENO STORE" fill sizes="(max-width: 640px) calc(100vw - 32px), 960px" className="object-cover object-center opacity-60" /><div className="relative"><h2 className="text-2xl font-black text-white">عروض وخصومات حصرية</h2><p className="mt-1 text-sm text-zinc-200">لا تفوت أفضل العروض على جميع المنتجات</p></div><Link href="/store/offers" className="relative mx-auto mt-3 inline-flex h-11 w-44 items-center justify-center rounded-full bg-red-600 px-4 text-base font-bold transition hover:bg-red-500 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-300">شاهد العروض <ChevronLeft className="mr-1 size-4" /></Link></section></div></div></main>
}
