'use client'

import { useMemo, useState, type ReactNode } from 'react'
import { Activity, AlertTriangle, ArrowDownLeft, ArrowUpLeft, Banknote, BarChart3, Bell, Boxes, CheckCircle2, ChevronDown, CircleDollarSign, Clock3, CreditCard, Gem, LayoutList, Package, Percent, Plus, ShoppingBag, TrendingUp, UserRound, Users, WalletCards, XCircle, Zap } from 'lucide-react'
import { AdminCard, AdminEmptyState, AdminErrorState, AdminLoadingState, AdminPageHeader, AdminSection, AdminToolbar } from '@/components/admin/admin-components'
import { dashboardPeriods, getDashboardData, type DashboardPeriod } from '@/lib/data/dashboard'
import { cn } from '@/lib/utils'

const toneClasses = { gold: 'bg-[#f5c542]/10 text-[#f5c542]', green: 'bg-[#45e0b2]/10 text-[#45e0b2]', red: 'bg-[#e50914]/10 text-[#ff6b72]', muted: 'bg-white/[.06] text-white/45' }
const IconMap = { sales: CircleDollarSign, orders: ShoppingBag, customers: Users, profit: TrendingUp, pending: Clock3, active: Activity, review: ClipboardIcon, withdraw: ArrowUpLeft, deposit: ArrowDownLeft, stock: Package, payment: CreditCard, order: ShoppingBag, wallet: WalletCards, edit: LayoutList }
function ClipboardIcon(props: React.ComponentProps<'svg'>) { return <LayoutList {...props} /> }

function DashboardPeriodFilter({ value, onChange }: { value: DashboardPeriod; onChange: (value: DashboardPeriod) => void }) {
  return <AdminToolbar><span className="text-xs font-bold text-white/60">الفترة الزمنية</span><div className="relative"><select aria-label="الفترة الزمنية" value={value} onChange={event => onChange(event.target.value as DashboardPeriod)} className="appearance-none rounded-xl border border-white/10 bg-white/[.04] py-2.5 pl-9 pr-3 text-xs font-bold text-white outline-none transition focus:border-[#f5c542]/50"><option className="bg-[#111518]" value="today">اليوم</option>{dashboardPeriods.slice(1).map(period => <option className="bg-[#111518]" key={period.value} value={period.value}>{period.label}</option>)}</select><ChevronDown className="pointer-events-none absolute left-2.5 top-1/2 size-3 -translate-y-1/2 text-white/40" /></div></AdminToolbar>
}

function DashboardKpiGrid({ data }: { data: ReturnType<typeof getDashboardData> }) {
  return <div className="grid grid-cols-2 gap-3 xl:grid-cols-3 2xl:grid-cols-6">{data.summary.map(item => { const Icon = IconMap[item.icon as keyof typeof IconMap] ?? Gem; return <AdminCard key={item.label} className="p-4 sm:p-5"><div className="flex items-start justify-between gap-2"><span className={cn('grid size-9 shrink-0 place-items-center rounded-xl', toneClasses[item.tone])}><Icon className="size-4" /></span>{item.change && <span className={cn('rounded-full px-2 py-1 text-[10px] font-bold', item.change.startsWith('-') ? toneClasses.red : toneClasses.green)}>{item.change}</span>}</div><p className="mt-5 text-[11px] text-white/45">{item.label}</p><p className="mt-1 text-base font-black tracking-tight text-white sm:text-lg">{item.value}</p><p className="mt-1 text-[10px] text-white/25">مقارنة بالفترة السابقة</p></AdminCard> })}</div>
}

function SalesChart({ data }: { data: ReturnType<typeof getDashboardData>['sales'] }) {
  const max = Math.max(...data.map(item => item.revenue))
  return <AdminCard className="p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="font-bold text-white">المبيعات</h2><p className="mt-1 text-xs text-white/40">أداء المبيعات خلال الفترة المحددة</p></div><div className="flex items-center gap-3 text-[10px] text-white/45"><span className="flex items-center gap-1.5"><span className="size-2 rounded-full bg-[#f5c542]" />الإيرادات</span><span className="flex items-center gap-1.5"><span className="size-2 rounded-full bg-[#45e0b2]" />الطلبات</span></div></div><div className="mt-6 flex h-52 items-end gap-2 border-b border-white/[.08] px-1 sm:gap-4">{data.map(item => <div className="flex min-w-0 flex-1 flex-col items-center justify-end gap-2" key={item.label}><div className="flex h-40 w-full max-w-9 items-end gap-1"><span title={`${item.revenue} ألف ج.م`} className="w-1/2 rounded-t-md bg-[#f5c542] transition-all" style={{ height: `${(item.revenue / max) * 100}%` }} /><span title={`${item.orders} طلب`} className="w-1/2 rounded-t-md bg-[#45e0b2]/70 transition-all" style={{ height: `${(item.orders / max) * 100}%` }} /></div><span className="truncate text-[10px] text-white/35">{item.label}</span></div>)}</div></AdminCard>
}

function OrdersOverview({ data }: { data: ReturnType<typeof getDashboardData>['ordersOverview'] }) { const total = data.reduce((sum, item) => sum + item.count, 0); return <AdminCard className="p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-bold text-white">نظرة عامة على الطلبات</h2><p className="mt-1 text-xs text-white/40">توزيع الطلبات حسب الحالة</p></div><span className="text-xl font-black text-white">{total.toLocaleString('ar-EG')}</span></div><div className="mt-6 flex h-3 overflow-hidden rounded-full bg-white/[.06]">{data.map(item => <span key={item.label} className={cn('h-full', item.tone === 'gold' && 'bg-[#f5c542]', item.tone === 'green' && 'bg-[#45e0b2]', item.tone === 'red' && 'bg-[#e50914]', item.tone === 'muted' && 'bg-white/20')} style={{ width: `${Math.max((item.count / total) * 100, 1)}%` }} />)}</div><div className="mt-5 grid grid-cols-2 gap-3">{data.map(item => <div key={item.label} className="flex items-center justify-between rounded-xl border border-white/[.07] bg-white/[.025] p-3"><span className="flex items-center gap-2 text-[11px] text-white/50"><span className={cn('size-2 rounded-full', item.tone === 'gold' && 'bg-[#f5c542]', item.tone === 'green' && 'bg-[#45e0b2]', item.tone === 'red' && 'bg-[#e50914]', item.tone === 'muted' && 'bg-white/25')} />{item.label}</span><strong className="text-sm text-white">{item.count.toLocaleString('ar-EG')}</strong></div>)}</div></AdminCard> }

function OperationsQueue({ data }: { data: ReturnType<typeof getDashboardData>['operations'] }) { return <AdminCard className="p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-bold text-white">يحتاج إلى إجراء</h2><p className="mt-1 text-xs text-white/40">عناصر تحتاج انتباه فريق الإدارة</p></div><Zap className="size-5 text-[#f5c542]" /></div><div className="mt-5 flex flex-col gap-2">{data.map(item => { const Icon = IconMap[item.icon as keyof typeof IconMap] ?? AlertTriangle; return <button type="button" key={item.label} onClick={() => undefined} className="flex items-center gap-3 rounded-xl border border-white/[.06] p-3 text-right transition hover:border-white/15 hover:bg-white/[.03]"><span className={cn('grid size-9 shrink-0 place-items-center rounded-xl', item.severity === 'critical' ? toneClasses.red : item.severity === 'warning' ? toneClasses.gold : toneClasses.muted)}><Icon className="size-4" /></span><span className="min-w-0 flex-1"><span className="block truncate text-xs font-semibold text-white/80">{item.label}</span><span className="mt-1 block text-[10px] text-white/30">الإجراء مطلوب</span></span><strong className="text-sm text-white">{item.count}</strong></button> })}</div></AdminCard> }

function RecentOrders({ data }: { data: ReturnType<typeof getDashboardData>['recentOrders'] }) { return <AdminCard className="overflow-hidden"><div className="flex items-center justify-between border-b border-white/[.08] p-5 sm:px-6"><div><h2 className="font-bold text-white">آخر الطلبات</h2><p className="mt-1 text-xs text-white/40">أحدث العمليات في المتجر</p></div><button type="button" onClick={() => undefined} className="text-[11px] font-bold text-[#f5c542] hover:text-[#ffdc78]">عرض جميع الطلبات</button></div><div className="overflow-x-auto"><div className="min-w-[620px]">{data.map(order => <div key={order.id} className="grid grid-cols-[1.1fr_1.3fr_1fr_.8fr_1fr_.8fr] items-center gap-3 border-b border-white/[.05] px-5 py-4 last:border-0 sm:px-6"><span className="text-xs font-bold text-white">{order.id}<span className="mt-1 block text-[10px] font-normal text-white/30">{order.time}</span></span><span className="text-xs text-white/65">{order.customer}</span><span className="text-xs text-white/55">{order.product}</span><span className="text-xs font-bold text-white">{order.amount}</span><span className={cn('w-fit rounded-full px-2 py-1 text-[10px] font-bold', toneClasses[order.tone])}>{order.status}</span><span className="text-left text-[10px] text-white/25">طلب رقمي</span></div>)}</div></div></AdminCard> }

function ActivityList({ data }: { data: ReturnType<typeof getDashboardData>['activity'] }) { return <AdminCard className="p-5 sm:p-6"><h2 className="font-bold text-white">آخر النشاطات</h2><p className="mt-1 text-xs text-white/40">سجل مختصر لأهم عمليات الإدارة</p><div className="mt-5 flex flex-col gap-4">{data.map(item => { const Icon = IconMap[item.icon as keyof typeof IconMap] ?? Activity; return <div key={item.label} className="flex gap-3"><span className="grid size-8 shrink-0 place-items-center rounded-lg border border-white/10 bg-white/[.03] text-[#f5c542]"><Icon className="size-3.5" /></span><div className="min-w-0"><p className="text-xs font-semibold text-white/80">{item.label}</p><p className="mt-1 truncate text-[10px] text-white/35">{item.detail}</p><p className="mt-1 text-[10px] text-white/25">{item.time}</p></div></div> })}</div></AdminCard> }

function TopProducts({ data }: { data: ReturnType<typeof getDashboardData>['topProducts'] }) { return <AdminCard className="p-5 sm:p-6"><h2 className="font-bold text-white">الأكثر مبيعًا</h2><p className="mt-1 text-xs text-white/40">أفضل المنتجات أداءً</p><div className="mt-5 flex flex-col gap-3">{data.map((item, index) => <div key={item.name} className="flex items-center gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-xl border border-[#f5c542]/20 bg-[#f5c542]/10 text-xs font-black text-[#f5c542]">{item.short}</span><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold text-white/80">{item.name}</p><p className="mt-1 text-[10px] text-white/35">{item.category} · {item.orders} طلب</p></div><span className="text-left text-xs font-bold text-white/75">{item.revenue}<span className="mt-1 block text-[10px] font-normal text-white/25">#{index + 1}</span></span></div>)}</div></AdminCard> }

function CategoryPerformance({ data }: { data: ReturnType<typeof getDashboardData>['categories'] }) { return <AdminCard className="p-5 sm:p-6"><h2 className="font-bold text-white">أداء الأقسام</h2><p className="mt-1 text-xs text-white/40">حصة المبيعات حسب القسم</p><div className="mt-5 flex flex-col gap-4">{data.map(item => <div key={item.name}><div className="flex items-center justify-between gap-3 text-xs"><span className="truncate text-white/70">{item.name}</span><span className="shrink-0 text-white/40">{item.sales}</span></div><div className="mt-2 flex items-center gap-2"><div className="h-1.5 flex-1 overflow-hidden rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-[#f5c542]" style={{ width: `${item.share}%` }} /></div><span className="w-8 text-left text-[10px] text-white/35">{item.share}%</span></div></div>)}</div></AdminCard> }

function FinancialSnapshot({ data }: { data: ReturnType<typeof getDashboardData>['financial'] }) { return <AdminCard className="p-5 sm:p-6"><h2 className="font-bold text-white">ملخص مالي</h2><p className="mt-1 text-xs text-white/40">نظرة سريعة على الوضع المالي</p><div className="mt-5 grid grid-cols-2 gap-3">{data.map(item => <div key={item.label} className="rounded-xl border border-white/[.06] p-3"><span className="block text-[10px] text-white/40">{item.label}</span><strong className={cn('mt-2 block text-sm', `text-${item.tone}`)}>{item.value}</strong></div>)}</div></AdminCard> }

function SystemAlerts({ data }: { data: ReturnType<typeof getDashboardData>['alerts'] }) { return <AdminCard className="p-5 sm:p-6"><div className="flex items-center gap-2"><Bell className="size-4 text-[#f5c542]" /><h2 className="font-bold text-white">تنبيهات النظام</h2></div><div className="mt-5 flex flex-col gap-2">{data.map(item => <div key={item.label} className="flex items-center gap-3 rounded-xl border border-white/[.06] p-3"><span className={cn('size-2 shrink-0 rounded-full', item.severity === 'critical' ? 'bg-[#e50914]' : item.severity === 'warning' ? 'bg-[#f5c542]' : 'bg-[#45e0b2]')} /><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold text-white/75">{item.label}</p><p className="mt-1 text-[10px] text-white/30">{item.time}</p></div><span className="text-[10px] text-white/35">{item.status}</span></div>)}</div></AdminCard> }

function QuickActions() { return <AdminCard className="p-5 sm:p-6"><h2 className="font-bold text-white">إجراءات سريعة</h2><p className="mt-1 text-xs text-white/40">اختصارات للوحدات القادمة</p><div className="mt-5 grid grid-cols-2 gap-2">{['إضافة منتج', 'إضافة قسم', 'إنشاء عرض', 'مراجعة الطلبات', 'طلبات الإيداع', 'طلبات السحب'].map(label => <button type="button" key={label} onClick={() => undefined} className="flex items-center gap-2 rounded-xl border border-white/[.07] bg-white/[.02] p-3 text-right text-[11px] font-semibold text-white/65 transition hover:border-[#f5c542]/30 hover:bg-[#f5c542]/[.06] hover:text-white"><Plus className="size-3.5 text-[#f5c542]" />{label}</button>)}</div></AdminCard> }

export function AdminDashboard() {
  const [period, setPeriod] = useState<DashboardPeriod>('7d')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(false)
  const data = useMemo(() => getDashboardData(period), [period])
  const refresh = () => { setError(false); setLoading(true); window.setTimeout(() => setLoading(false), 450) }
  return <div><AdminPageHeader title="لوحة التحكم" description="نظرة عامة على أداء متجر Seno Store والعمليات الحالية" breadcrumbs={[{ label: 'الرئيسية', href: '/admin' }, { label: 'لوحة التحكم' }]} actions={<DashboardPeriodFilter value={period} onChange={setPeriod} />} />{error ? <AdminCard><AdminErrorState title="تعذر تحميل بيانات لوحة التحكم" onRetry={refresh} /></AdminCard> : loading ? <AdminCard><AdminLoadingState message="جاري تحميل بيانات لوحة التحكم..." /></AdminCard> : <div className="flex flex-col gap-5"><DashboardKpiGrid data={data} /><div className="grid gap-5 xl:grid-cols-[1.45fr_1fr]"><SalesChart data={data.sales} /><OrdersOverview data={data.ordersOverview} /></div><div className="grid gap-5 xl:grid-cols-[1fr_1.2fr]"><OperationsQueue data={data.operations} /><FinancialSnapshot data={data.financial} /></div><RecentOrders data={data.recentOrders} /><div className="grid gap-5 lg:grid-cols-3"><TopProducts data={data.topProducts} /><CategoryPerformance data={data.categories} /><ActivityList data={data.activity} /></div><div className="grid gap-5 lg:grid-cols-[1fr_1.2fr]"><SystemAlerts data={data.alerts} /><QuickActions /></div></div>}</div>
}
